### ISSUE TITLE
End2end EE and EL

### ISSUE THREAD

**Issue by ealmazanm** [clovaai/bros#2]
Hi, 
first of all thanks for the code, that's a great contribution to the community!!. From the paper I understood that the model could be fine-tuned end2end for EE and EL at the same time, however looking at the code I think it does not do it like that, right? Is it supported the combined EE and EL end2end somehow?

Thanks,

**Comment by tghong** [comment]
Hi, thank you for your interest.
As you understood, the model can be fine-tuned for EE and EL tasks at the same time.
It can be done by adding the loss (itc_loss + stc_loss) in `model/bros_spade.py` and the loss in `model/bros_spade_rel.py`.

https://github.com/clovaai/bros/blob/55c52d0872ed61fb7586b70618f45dcb0354f1b2/model/bros_spade.py#L101-L110

https://github.com/clovaai/bros/blob/55c52d0872ed61fb7586b70618f45dcb0354f1b2/model/bros_spade_rel.py#L93-L123

**Comment by unleft** [comment]
Hello, I have had the same question, but I would like to ask how exactly I can implement the mentioned feature.

Should I create a completely new Model and Module class from scratch... Or is there another way to make it work?
